### PR TITLE
Updated Counterclockwise URL, added Cursive entry.

### PR DESCRIPTION
**Pull request by asampal**

### CODE REVIEW

**Comment by arrdem** [comment]
nREPL is a contrib project which means that it is managed over on the Clojure JIRA tracker. Pull requests are sadly ignored and the (easy, electronic) Clojure Contributor Agreement is required.

Sorry.

**Comment by asampal** [comment]
Sorry, I'm not clear then on what you're suggesting I should do. I have no problem completing the CCA, but are you saying that even then, PRs will be ignored?

**Comment by arrdem** [comment]
Sadly. You'll have to go file an issue over on JIRA after signing the CA to get a JIRA account.

**Comment by jafingerhut** [comment]
You can create a JIRA account without signing the CA.  Just go here: http://dev.clojure.org/jira/browse/NREPL

Then click the "Log in" link near the upper right, and "Sign up" on the next page.  After you have a JIRA account and you are signed in, there is a link to create a new defect or enhancement ticket near the top right of the page.

**Comment by cemerick** [comment]
Can't directly apply your patch (since you've not submitted a CA), but I've applied the corrections to master directly.

Thanks/sorry! :-)

**Comment by asampal** [comment]
Strange, but I _have_ completed the CA (on the 8th, before submitting the
issue), as you can see from the body of the email sent to me here:

Clojure CA between Rich Hickey and Adrian Sampaleanu is Signed and Filed!

From: Rich Hickey (Rich Hickey)
To: Rich Hickey and Adrian Sampaleanu


 Attached is a final copy of *Clojure CA*.

Copies have been automatically sent to all parties to the agreement.

You can view *the document*
<https://secure.echosign.com/public/viewAgreement?tsid=2AAABLblqZhDS3Puni5cEZbptHmIa501kMr-8UYNtZ54JrHIjUjkd-WW0PwQAIr72lePyhcwX8SY*&>
in your Adobe Document Cloud account.

Why use Adobe Document Cloud:

   - Exchange, Sign, and File Any Document. In Seconds!
   - Set-up Reminders. Instantly Share Copies with Others.
   - See All of Your Documents, Anytime, Anywhere.


I've been waiting to appear on the list of people who completed it yet I
haven't, so it looks like something is up somewhere in the chain.


Cheers,

Adrian

**Comment by cemerick** [comment]
All I have to go by is http://clojure.org/contributing, which I assume is updated only periodically…

**Comment by asampal** [comment]
Should I create a JIRA issue for updating the page? :-)

**Pull request closed without merging**
